### ISSUE TITLE
Name service starting

### ISSUE THREAD

**Issue by meandor** [meandor/vs2017#18]

**Comment by meandor** [comment]
@falcowinkler what was done here?

**Comment by falcowinkler** [comment]
with werkzeug:ensureNameserviceStarted/0 you can start the name service if it has not been started already.

**Comment by meandor** [comment]
but what was done here? which commits correspond to this? what was acutally changed?

**Comment by meandor** [comment]
@falcowinkler should this really be done here? keep it simple and stupid!

just put in whereis for the nameservice ->less complexity and less work to do for our application.

also for the tests: the tests shouldnt start a nameservice as units of our modules are tested. we can assume the nameservice works so no nameservice functionality should be tested!
-> use mock of nameservice!

**Comment by falcowinkler** [comment]
ok, so i will write a name service mock and remove the ensure method and only start the name service once in production, when the coordinator starts up

**Comment by meandor** [comment]
@falcowinkler maybe klauck will even start a nameservice on which we should attach, nobody knows

**Comment by falcowinkler** [comment]
but for now, we need a method that starts our own service, to test everything

**Comment by falcowinkler** [comment]
but we should also see that it is decoupled, right

**Comment by meandor** [comment]
i will write a hint in the readme, that should be enough,
so if you wanna start a nameservice look it up in the readme on how to start one
