### ISSUE TITLE
Implement Koordinator

### ISSUE THREAD

**Issue by meandor** [meandor/vs2017#19]

**Comment by meandor** [comment]
@falcowinkler does the interface return the quota via {FROM, getsteeringval} as an absolute number?

**Comment by falcowinkler** [comment]
Yes it has to

**Comment by falcowinkler** [comment]
Absolute Number can be calculated by taking the percentage value from config and applying it to the current legth of the ggt process list

**Comment by meandor** [comment]
@falcowinkler current length of the list or the configured number of ggt processes?

**Comment by falcowinkler** [comment]
Current length, it says somewhere in the task description, quota will be calculated based on the clients currently known

**Comment by falcowinkler** [comment]
He also said it in the lecture

**Comment by meandor** [comment]
- [ ] quota in get steering vals has to be Current length, it says somewhere in the task description, quota will be calculated based on the clients currently known

**Comment by meandor** [comment]
Refactored ggt ring building and added tests for it

**Comment by meandor** [comment]
please test
