### ISSUE TITLE
neptr - add proxy translator

### ISSUE THREAD

**Issue by meandor** [meandor/vs2017#42]
create proxy class that implements the stub and calls the methods over the orb remotely

**Comment by meandor** [comment]
better test plox

- [ ] modify end-to-end test to check for both created java classes
- [ ] use correct namespaces for objectref
- [ ] test the whole proxy translator instead of only end to end - take a look at the exisiting translator test
- [ ] does TranslatorUtil have to exist? and does it have to be public access?

**Comment by falcowinkler** [comment]
without translator util we duplicate code
