### ISSUE TITLE
implement hbq

### ISSUE THREAD

**Issue by meandor** [meandor/vs2017#7]
Da die dem Server zugestellten Textzeilen bzgl. der Nummerierung in zusammenhängender Reihenfolge erscheinen sollen und Nachrichten mit Textzeilen verloren gehen können bzw. in nicht sortierter Reihenfolge eintreffen können, arbeitet der Server intern mit einer Deliveryqueue (DLQ) und einer Holdbackqueue (HBQ).
In der Deliveryqueue stehen die Nachrichten, die an Clients ausgeliefert werden können, maximal *** viele Textzeilen. Dies wird durch die Größe der Deliveryqueue vorgegeben.
In der Holdbackqueue stehen alle Textzeilen, die nicht ausgeliefert werden dürfen.

Der Server verwendet drei ADTs: HBQ (Datei hbq.erl), DLQ (Datei dlq.erl) und CMEM (Datei cmem.erl) als Gedächtnis für die Leser-Clients. Diese dürfen hauptsächlich nur als Erlang-Liste ([ ]) realisiert werden! Als Hilfsstrukturen dürfen Tupel eingesetzt werden. Dazu sind die weiter unten aufgeführten Vorgaben zu beachten!

Die HBQ ist als entfernte ADT zu implementieren. Ihre Schnittstelle ist daher durch Nachrichtenformate beschrieben. Die DLQ oder das CMEM sind als lokale ADT zu implementieren. Daher sind deren Schnittstellen durch Funktionen beschrieben. Intern kann die DLQ bzw. das CMEM jedoch als externer Prozess realisiert werden! 

Wenn in der Holdbackqueue von der Anzahl her mehr als 2/3-tel an echten Nachrichten enthalten sind, als durch die vorgegebene maximale Anzahl an Nachrichten in der Deliveryqueue stehen können, dann wird, sofern eine Lücke besteht, diese Lücke zwischen Deliveryqueue und Holdbackqueue mit genau einer Fehlernachricht geschlossen, etwa: ***Fehlernachricht fuer Nachrichtennummern 11 bis 17 um 16.05 18:01:30,580|. Es werden keine weiteren Lücken innerhalb der Holdbackqueue behandelt! In dem Sinne wird die Holdbackqueue in diesem Fall nicht zwingend geleert. Die Fehlernachrciht ist nur durch eine entsprechende Zeichenkette in der Nachricht zu erkennen. Ansonsten hat sie das Format einer ganz normalen Nachricht, d.h. das System kann eine Fehlernachricht nach Speicherung in der DLQ nicht mehr als solche erkennen!

**Comment by meandor** [comment]
and dont forget to update docu

**Comment by meandor** [comment]
Im Folgenden wird die Schnittstelle der HBQ des Servers beschrieben.

                /* Initialisieren der HBQ */
                HBQ ! {self(), {request,initHBQ}}
                receive {reply, ok} 
                Beispiel:  HBQ ! {<7016.50.0>, {request,initHBQ}}
                                 receive {reply, ok}

                /* Speichern einer Nachricht in der HBQ */
                HBQ ! {self(), {request,pushHBQ,[NNr,Msg,TSclientout]}}
                receive {reply, ok} 
                Beispiel:  HBQ ! {<7016.50.0>,  {request,pushHBQ,[15,  "0-pclient@KI-VS-<0.64.0>-KLC: 15te_Nachricht. C Out: 29.04 08:43:24,871| ", {1430,289804,872001}]}}
                                 receive {reply, ok}

                /* Abfrage einer Nachricht */
                HBQ ! {self(), {request,deliverMSG,NNr,ToClient}}
                receive {reply, SendNNr}
                Beispiel:  HBQ ! {<7016.50.0>, {request,deliverMSG,15,<7298.65.0>}}
                                 receive {reply, 18}

                /* Terminierung der HBQ */
                HBQ ! {self(), {request,dellHBQ}}
                receive {reply, ok} 
                Beispiel:  HBQ ! {<7016.50.0>, {request,dellHBQ,}}
                                 receive {reply, ok}

{request,initHBQ}: initialisiert die HBQ und die DLQ. Bei Erfolg wird ein ok gesendet.

{request,pushHBQ,[NNr,Msg,TSclientout]}: fügt eine Nachricht Msg (Textzeile) mit Nummer NNr und dem Sende-Zeitstempel TSclientout (mit erlang:now() erstellt) in die HBQ ein. Bei Erfolg wird ein ok gesendet.

{request,deliverMSG,NNr,ToClient}: beauftragt die HBQ über die DLQ die Nachricht mit der Nummer NNr (falls nicht verfügbar die nächst höhere Nachrichtennummer) an den Client ToClient (als PID) auszuliefern. Bei Erfolg wird die tatsächlich gesendete Nachrichtennummer SendNNr gesendet.

{request,dellHBQ}: terminiert den Prozess der HBQ. Bei Erfolg wird ein ok gesendet.

**Comment by meandor** [comment]
beim push wird geschaut, ob nachrichten direkt in die dlq gehen könne.

falls nicht, werden sie in der hbq gespeichert (weil ungültig). wenn dadurch der fehler nachrichten threshold erreicht wird, wird die fehlerbehandlung eingeleitet

**Comment by falcowinkler** [comment]
Die Bedingung dass nachrichten in die DLQ gehen ist: Expected NNR  = Eintreffende Nachricht NNR

**Comment by falcowinkler** [comment]
Wenn das nicht der fall ist wird die Nachricht sortiert gespeichert, und dann die Liste vom Anfang nach gültigen nachrichten gescannt

**Comment by meandor** [comment]
@falcowinkler ich bin mir immer noch unsicher ob wir sortieren sollten

**Comment by falcowinkler** [comment]
Ich versuche es erstmal so, ich denke es ist der einfachste weg

**Comment by meandor** [comment]
added tests
